//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomControl {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomControl.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 连接状态 的本地化字符串。
        /// </summary>
        internal static string ConnectState_CN {
            get {
                return ResourceManager.GetString("ConnectState_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection status 的本地化字符串。
        /// </summary>
        internal static string ConnectState_EN {
            get {
                return ResourceManager.GetString("ConnectState_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 連接狀態 的本地化字符串。
        /// </summary>
        internal static string ConnectState_HK {
            get {
                return ResourceManager.GetString("ConnectState_HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更新时间: 的本地化字符串。
        /// </summary>
        internal static string lastUpdateTime_CN {
            get {
                return ResourceManager.GetString("lastUpdateTime_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last update time: 的本地化字符串。
        /// </summary>
        internal static string lastUpdateTime_EN {
            get {
                return ResourceManager.GetString("lastUpdateTime_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最後更新時間: 的本地化字符串。
        /// </summary>
        internal static string lastUpdateTime_HK {
            get {
                return ResourceManager.GetString("lastUpdateTime_HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兆 的本地化字符串。
        /// </summary>
        internal static string MByte_CN {
            get {
                return ResourceManager.GetString("MByte_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MByte 的本地化字符串。
        /// </summary>
        internal static string MByte_EN {
            get {
                return ResourceManager.GetString("MByte_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兆 的本地化字符串。
        /// </summary>
        internal static string MByte_HK {
            get {
                return ResourceManager.GetString("MByte_HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        internal static string Min_CN {
            get {
                return ResourceManager.GetString("Min_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min 的本地化字符串。
        /// </summary>
        internal static string Min_EN {
            get {
                return ResourceManager.GetString("Min_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分鍾 的本地化字符串。
        /// </summary>
        internal static string Min_HK {
            get {
                return ResourceManager.GetString("Min_HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未登录或已断开连接 的本地化字符串。
        /// </summary>
        internal static string TileContent_Disconn_CN {
            get {
                return ResourceManager.GetString("TileContent_Disconn_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not logged in or Disconnected 的本地化字符串。
        /// </summary>
        internal static string TileContent_Disconn_EN {
            get {
                return ResourceManager.GetString("TileContent_Disconn_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未登錄或已斷開連接 的本地化字符串。
        /// </summary>
        internal static string TileContent_Disconn_HK {
            get {
                return ResourceManager.GetString("TileContent_Disconn_HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用流量: 的本地化字符串。
        /// </summary>
        internal static string Used_flux_CN {
            get {
                return ResourceManager.GetString("Used_flux_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Used flux: 的本地化字符串。
        /// </summary>
        internal static string Used_flux_EN {
            get {
                return ResourceManager.GetString("Used_flux_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用流量: 的本地化字符串。
        /// </summary>
        internal static string Used_flux_HK {
            get {
                return ResourceManager.GetString("Used_flux_HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用时长: 的本地化字符串。
        /// </summary>
        internal static string Used_time_CN {
            get {
                return ResourceManager.GetString("Used_time_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Used time: 的本地化字符串。
        /// </summary>
        internal static string Used_time_EN {
            get {
                return ResourceManager.GetString("Used_time_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用時長: 的本地化字符串。
        /// </summary>
        internal static string Used_time_HK {
            get {
                return ResourceManager.GetString("Used_time_HK", resourceCulture);
            }
        }
    }
}
