//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrClient4Wp8.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrClient4Wp8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单项 的本地化字符串。
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的应用程序 的本地化字符串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动登录 的本地化字符串。
        /// </summary>
        public static string autoLogin {
            get {
                return ResourceManager.GetString("autoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登  录 的本地化字符串。
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注  销 的本地化字符串。
        /// </summary>
        public static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要退出客户端吗? 的本地化字符串。
        /// </summary>
        public static string closingMsgTip {
            get {
                return ResourceManager.GetString("closingMsgTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string closingMsgTitle {
            get {
                return ResourceManager.GetString("closingMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接状态 的本地化字符串。
        /// </summary>
        public static string ConnectState {
            get {
                return ResourceManager.GetString("ConnectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前网络 的本地化字符串。
        /// </summary>
        public static string CurrentNetwork {
            get {
                return ResourceManager.GetString("CurrentNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID: 的本地化字符串。
        /// </summary>
        public static string DeviceID {
            get {
                return ResourceManager.GetString("DeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此帐号已停用 的本地化字符串。
        /// </summary>
        public static string DrClient_AccountBreakOff {
            get {
                return ResourceManager.GetString("DrClient_AccountBreakOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此帐号不允许使用WiFi认证登录 的本地化字符串。
        /// </summary>
        public static string DrClient_AccountNotAllow {
            get {
                return ResourceManager.GetString("DrClient_AccountNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此帐号正在使用中，请联系网络管理员 IP({0}) MAC({1}) 的本地化字符串。
        /// </summary>
        public static string DrClient_AccountTieUp {
            get {
                return ResourceManager.GetString("DrClient_AccountTieUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此设备已接入互联网，无需登录 的本地化字符串。
        /// </summary>
        public static string DrClient_AlreadyOnline {
            get {
                return ResourceManager.GetString("DrClient_AlreadyOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此帐号费用超支或时长流量超过限制 的本地化字符串。
        /// </summary>
        public static string DrClient_ChargeOrFluxOver {
            get {
                return ResourceManager.GetString("DrClient_ChargeOrFluxOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的帐号或密码，请重新登录 的本地化字符串。
        /// </summary>
        public static string DrClient_InvalidAccountOrPwd {
            get {
                return ResourceManager.GetString("DrClient_InvalidAccountOrPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此IP不允许使用WiFi认证登录 的本地化字符串。
        /// </summary>
        public static string DrClient_IpNotAllowLogin {
            get {
                return ResourceManager.GetString("DrClient_IpNotAllowLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络连接中断，请检查网络配置 的本地化字符串。
        /// </summary>
        public static string DrClient_NetworkError {
            get {
                return ResourceManager.GetString("DrClient_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新设定的密码与确认密码不同，修改失败 的本地化字符串。
        /// </summary>
        public static string DrClient_NewAndConfirmPwdDiffer {
            get {
                return ResourceManager.GetString("DrClient_NewAndConfirmPwdDiffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此帐号不允许更改密码 的本地化字符串。
        /// </summary>
        public static string DrClient_NotAllowChangePwd {
            get {
                return ResourceManager.GetString("DrClient_NotAllowChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前网络 {0} 不支持认证登录 的本地化字符串。
        /// </summary>
        public static string DrClient_NotFoundDrCOM {
            get {
                return ResourceManager.GetString("DrClient_NotFoundDrCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码修改成功 的本地化字符串。
        /// </summary>
        public static string DrClient_PwdAmendSuccessed {
            get {
                return ResourceManager.GetString("DrClient_PwdAmendSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string DrClient_Success {
            get {
                return ResourceManager.GetString("DrClient_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统缓存已满 的本地化字符串。
        /// </summary>
        public static string DrClient_SystemBufferFull {
            get {
                return ResourceManager.GetString("DrClient_SystemBufferFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此帐户被占用，不能修改 的本地化字符串。
        /// </summary>
        public static string DrClient_TieUpCannotAmend {
            get {
                return ResourceManager.GetString("DrClient_TieUpCannotAmend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误 的本地化字符串。
        /// </summary>
        public static string DrClient_UndefineError {
            get {
                return ResourceManager.GetString("DrClient_UndefineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此帐号只能使用指定的MAC登录 MAC({0}) 的本地化字符串。
        /// </summary>
        public static string DrClient_UsingAppointedMac {
            get {
                return ResourceManager.GetString("DrClient_UsingAppointedMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此帐号不允许使用 NAT 的本地化字符串。
        /// </summary>
        public static string DrClient_UsingNAT {
            get {
                return ResourceManager.GetString("DrClient_UsingNAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此帐号只能使用指定的IP登录 IP({0}) 的本地化字符串。
        /// </summary>
        public static string DrClient_UsingOnAppointedIp {
            get {
                return ResourceManager.GetString("DrClient_UsingOnAppointedIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名和密码不能为空 的本地化字符串。
        /// </summary>
        public static string EmptyUsernameOrPassword {
            get {
                return ResourceManager.GetString("EmptyUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更新时间: 的本地化字符串。
        /// </summary>
        public static string lastUpdateTime {
            get {
                return ResourceManager.GetString("lastUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在登录... 的本地化字符串。
        /// </summary>
        public static string loggingText {
            get {
                return ResourceManager.GetString("loggingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在注销... 的本地化字符串。
        /// </summary>
        public static string logoutText {
            get {
                return ResourceManager.GetString("logoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兆 的本地化字符串。
        /// </summary>
        public static string MByte {
            get {
                return ResourceManager.GetString("MByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密   码: 的本地化字符串。
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftToRight 的本地化字符串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-cn 的本地化字符串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存密码 的本地化字符串。
        /// </summary>
        public static string savePassword {
            get {
                return ResourceManager.GetString("savePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未登录或已断开连接 的本地化字符串。
        /// </summary>
        public static string TileContent_Disconn {
            get {
                return ResourceManager.GetString("TileContent_Disconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本，是否进行升级? 的本地化字符串。
        /// </summary>
        public static string Upgrade_msg {
            get {
                return ResourceManager.GetString("Upgrade_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级提示 的本地化字符串。
        /// </summary>
        public static string UpgradeTips {
            get {
                return ResourceManager.GetString("UpgradeTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用流量: 的本地化字符串。
        /// </summary>
        public static string Used_flux {
            get {
                return ResourceManager.GetString("Used_flux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用时长: 的本地化字符串。
        /// </summary>
        public static string Used_time {
            get {
                return ResourceManager.GetString("Used_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名: 的本地化字符串。
        /// </summary>
        public static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备未接入无线局域网(WLAN) 的本地化字符串。
        /// </summary>
        public static string WlanNotConnected {
            get {
                return ResourceManager.GetString("WlanNotConnected", resourceCulture);
            }
        }
    }
}
