/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_drcom_Android_DrCOMWS_Jni */

#ifndef _Included_com_drcom_Android_DrCOMWS_Jni
#define _Included_com_drcom_Android_DrCOMWS_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    httpLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_drcom_Android_DrCOMWS_Jni_httpLogin
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    httpLoginCheck
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_drcom_Android_DrCOMWS_Jni_httpLoginCheck
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    httpLoginAuth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_drcom_Android_DrCOMWS_Jni_httpLoginAuth
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    httpLogout
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_drcom_Android_DrCOMWS_Jni_httpLogout
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    getGatewayAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_drcom_Android_DrCOMWS_Jni_getGatewayAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    setGatwatAddress
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_drcom_Android_DrCOMWS_Jni_setGatwatAddress
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    getLoginStatus
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_drcom_Android_DrCOMWS_Jni_getLoginStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    setSSID
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_drcom_Android_DrCOMWS_Jni_setSSID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    httpStatus
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_drcom_Android_DrCOMWS_Jni_httpStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    getFluxStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_drcom_Android_DrCOMWS_Jni_getFluxStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    getTimeStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_drcom_Android_DrCOMWS_Jni_getTimeStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    getUnfineError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_drcom_Android_DrCOMWS_Jni_getUnfineError
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    getXip
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_drcom_Android_DrCOMWS_Jni_getXip
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    getMac
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_drcom_Android_DrCOMWS_Jni_getMac
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_Android_DrCOMWS_Jni
 * Method:    getData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_drcom_Android_DrCOMWS_Jni_getData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
